apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: ob-net-core-dwiki
  name: ob-net-core-dwiki
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ob-net-core-dwiki
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: ob-net-core-dwiki
      name: ob-net-core-dwiki
    spec:
      containers:
        - name: ob-net-core-dwiki
          image: acronboarding.azurecr.io/ob-net-core-dwiki:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: secret-dwiki
                  key: ob-core-db
            - name: AuthorizationServer__Address
              valueFrom:
                configMapKeyRef:
                  name: map-dwiki
                  key: ob-core-config
          ports:
          - containerPort: 80
          resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 125m
                memory: 256Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ob-net-core-dwiki
  name: ob-net-core-dwiki
spec:
  ports:
  - port: 80
  type: LoadBalancer
  selector:
    app: ob-net-core-dwiki
status:
  loadBalancer: {}
